
name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create executables folder
      run: mkdir -p executables

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2

    - name: Build
      run: go build -o ./executables -v ./...

    - name: Archive executables
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: executables

    - name: ls command
      run: |
            ls
            pwd
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download executables artifact
        uses: actions/download-artifact@v2
        with:
          name: executables
          path: executables/
          
      - name: List downloaded files
        run: ls -R executables

      - name: Make mongoapi executable
        run: chmod +x executables/mongoapi

      - name: Run executable
        run: ./executables/mongoapi  &


      - name: Snap Install ngrok
        run: sudo snap install ngrok --devmode

      - name: Start ngrok and expose ports
        run: |
          sudo ngrok authtoken 1x4H0neaMfnRX0ATJsuLhMP3lt3_tEj68PPQBGSMmY8wZMHH
          sudo ngrok http 4000

      - name: Snap Install ngrok
        run: sudo snap install ngrok --devmode

      - name: Start ngrok and expose ports
        run: |
          sudo ngrok authtoken 1x4H0neaMfnRX0ATJsuLhMP3lt3_tEj68PPQBGSMmY8wZMHH
          sudo ngrok http 4000
