name: Execute Build

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start execution
        run: echo "Starting execution..."

  execute_build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download executables artifact
        uses: actions/download-artifact@v2
        with:
          name: executables
          path: executables

      - name: Run executable
        run: ./executables/your_executable_name
