name: Execute Build

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed

jobs:
  execute_build:
    runs-on: ubuntu-latest
    steps:
      - name: Download executables artifact
        uses: actions/download-artifact@v2
        with:
          name: executables
          path: executables/
          
      - name: List downloaded files
        run: ls -R executables

      - name: Run executable
        run: ./executables/your_executable_name
